version: "3.2"
services:
  redis:
    image: redis:3.2-alpine
    ports:
      - target: 6379
        published: 6379
        mode: host
  mongodb:
    image: mongo:3.6
    ports:
      - target: 27017
        published: 27017
        mode: host
